Visualización de rutina y ejercicios de la rutina + conexión con la Db
ValentinMarchessi/training-app-client pull request #83
Opened 2022-02-26 00:36 UTC by Galaximar

2022-02-26 03:25 UTC, ValentinMarchessi approved these changes

2022-02-26 03:26 UTC, ValentinMarchessi commented
Agrega el package-lock al .gitignore

2022-02-28 18:13 UTC, ValentinMarchessi requested changes

2022-02-28 18:13 UTC, ValentinMarchessi commented on src/Pages/Routines/RoutineDetail/Routine.jsx
> +                                    {days.map((d,i)=><option value={i} key={i}>{d}</option>)}
days no está definido

2022-03-01 15:03 UTC, Galaximar commented on src/Pages/Routines/RoutineDetail/Routine.jsx
> +                                    {days.map((d,i)=><option value={i} key={i}>{d}</option>)}
Arreglado

2022-03-01 17:20 UTC, ValentinMarchessi approved these changes

2022-03-01 17:20 UTC, merged